create table tb_hmaster (
ID_Customer varchar(10) NULL comment 'ID' ,
Campany_Name varchar(50) NULL comment '会社名' ,
Name_Customer varchar(50) NULL comment '担当員' ,
NN_SEC1 varchar(50) NULL comment '所番地分類1' ,
NN_SEC2 varchar(50) NULL comment '所番地分類2' ,
NN_SEC3 varchar(50) NULL comment '所番地分類3' ,
NN_SEC4 varchar(50) NULL comment '所番地分類4' ,
NN_SEC5 varchar(50) NULL comment '置き場1' ,
Campany_Name varchar(50) NULL comment 'db_path' ,
Campany_Name varchar(50) NULL comment 'data_path' ,
f_AutoCreateDATA bit(1) NULL comment '自動作成機能' ,
f_DISP_ManageStatus bit(1) NULL comment '管理状態表示' ,
f_DISP_InspectCycle bit(1) NULL comment '検査周期表示' ,
f_DISP_DATAConfirmation bit(1) NULL comment 'データ確認欄表示' ,
f_DISP_CALRisultDetails bit(1) NULL comment '校正結果詳細表示' ,
f_DISP_Expired bit(1) NULL comment '期限切れ表示' ,
f_DISP_CALPlans bit(1) NULL comment '校正予定表示' ,
f_DISP_VariousLIST bit(1) NULL comment '各種リスト表示' ,
f_NEWCreate bit(1) NULL comment '新規作成' ,
f_Changable bit(1) NULL comment '変更' ,
f_Disposal bit(1) NULL comment '廃棄' ,
f_SuportReport bit(1) NULL comment '補助資料' ,
f_NGList bit(1) NULL comment '不合格報告書' ,
f_CautionList bit(1) NULL comment '要注意報告書' ,
f_ImplementationList bit(1) NULL comment '実施リスト' ,
f_MasterInfoManage bit(1) NULL comment 'マスター情報管理' ,
f_UseSEC1 bit(1) NULL comment '所番地1' ,
f_UseSEC2 bit(1) NULL comment '所番地2' ,
f_UseSEC3 bit(1) NULL comment '所番地3' ,
f_UseSEC4 bit(1) NULL comment '所番地4' ,
f_UseSEC4 bit(1) NULL comment '置き場1表示' ,
f_ChangeManege bit(1) NULL comment '変更管理' ,
f_AcceptanceInfo bit(1)  comment '入荷情報' 

) ENGINE=InnoDB;
