

<DIV id="headmenu" class="noprint" >

<ul class="globalNav">
  <li class="triangle"><a href="#"></a></li>
  <li><a href="search.php"><strong>戻る</strong><span>back</span></a></li>
  <li><a href="search.php"><strong>検索メニュー</strong><span>search menu</span></a></li>
  <li><a href="menu.php"><strong>メニュー</strong><span>home menu</span></a></li>
  <li><a href="logout.php"><strong>ログアウト</strong><span>logout</span></a></li>
</ul>
</div>